kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: duckhunt
  labels:
    app: duckhunt
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: duckhunt
  template:
    metadata:
      labels:
        deployment: duckhunt
        app: duckhunt
    spec:
      containers:
        - name: duckhunt
          image: quay.io/sbergste/duckhunt:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: duckhunt
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: duckhunt
