{
 "title": "Custom Metrics Example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mytimer",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rate(mytimer_sum[5m])" }
   ]
  },
  {
   "title": "mygauge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 0 },
   "targets": [
    { "expr": "mygauge" }
   ]
  },
  {
   "title": "myconter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "mycounter_total" }
   ]
  }
 ]
}